# ==========================================
# CONFIGURACIÓN DE LA TERMINAL (KITTY)
# ==========================================

# 1. Márgenes internos (El salvavidas del texto)
# Esto empuja el texto 15 píxeles hacia el centro para que Hyprland no lo recorte
window_padding_width 15

# 2. Integración total con Pywal (Colores dinámicos)
# Kitty leerá esta paleta generada automáticamente cada vez que cambies de fondo
include ~/.cache/colors/kitty.conf

# 3. Tipografía (Ajusta el tamaño a tu gusto)
font_family      Hack Nerd Font
font_size        12.0

# 4. Estética de la ventana
# Ocultamos la barra de título nativa porque Hyprland ya gestiona la ventana
hide_window_decorations yes
confirm_os_window_close 0

# 5. Comodidad
# Desactiva el molesto "beep" cuando cometes un error en la terminal
enable_audio_bell no

# 6. Transparencia (Efecto cristal)
# El valor va de 0.0 (totalmente invisible) a 1.0 (sólido). 0.8 o 0.85 suele ser el punto dulce.
background_opacity 0.80
shell zsh

